//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: player.proto
namespace player
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Player")]
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _cups;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cups", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cups
    {
      get { return _cups; }
      set { _cups = value; }
    }
    private int _sheild;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"sheild", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sheild
    {
      get { return _sheild; }
      set { _sheild = value; }
    }
    private readonly global::System.Collections.Generic.List<Player.AchievementState> _achi = new global::System.Collections.Generic.List<Player.AchievementState>();
    [global::ProtoBuf.ProtoMember(7, Name=@"achi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Player.AchievementState> achi
    {
      get { return _achi; }
    }
  
    private readonly global::System.Collections.Generic.List<Player.PveState> _pveState = new global::System.Collections.Generic.List<Player.PveState>();
    [global::ProtoBuf.ProtoMember(8, Name=@"pveState", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Player.PveState> pveState
    {
      get { return _pveState; }
    }
  
    private readonly global::System.Collections.Generic.List<Player.OwnedHeroState> _ownedHeros = new global::System.Collections.Generic.List<Player.OwnedHeroState>();
    [global::ProtoBuf.ProtoMember(9, Name=@"ownedHeros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Player.OwnedHeroState> ownedHeros
    {
      get { return _ownedHeros; }
    }
  
    private readonly global::System.Collections.Generic.List<Player.MineState> _mines = new global::System.Collections.Generic.List<Player.MineState>();
    [global::ProtoBuf.ProtoMember(10, Name=@"mines", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Player.MineState> mines
    {
      get { return _mines; }
    }
  
    private Player.GroupDefinition _groupInfo = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"groupInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Player.GroupDefinition groupInfo
    {
      get { return _groupInfo; }
      set { _groupInfo = value; }
    }
    private long _lastVersion = default(long);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"lastVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastVersion
    {
      get { return _lastVersion; }
      set { _lastVersion = value; }
    }
    private long _lastLowLotteryTime = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"lastLowLotteryTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastLowLotteryTime
    {
      get { return _lastLowLotteryTime; }
      set { _lastLowLotteryTime = value; }
    }
    private long _lastMidLotteryTime = default(long);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"lastMidLotteryTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastMidLotteryTime
    {
      get { return _lastMidLotteryTime; }
      set { _lastMidLotteryTime = value; }
    }
    private readonly global::System.Collections.Generic.List<Player.PveCharpter> _pveCharpter = new global::System.Collections.Generic.List<Player.PveCharpter>();
    [global::ProtoBuf.ProtoMember(15, Name=@"pveCharpter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Player.PveCharpter> pveCharpter
    {
      get { return _pveCharpter; }
    }
  
    private int _scene = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"scene", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int scene
    {
      get { return _scene; }
      set { _scene = value; }
    }
    private int _charpter = (int)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"charpter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int charpter
    {
      get { return _charpter; }
      set { _charpter = value; }
    }
    private readonly global::System.Collections.Generic.List<Player.Activity> _activity = new global::System.Collections.Generic.List<Player.Activity>();
    [global::ProtoBuf.ProtoMember(18, Name=@"activity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Player.Activity> activity
    {
      get { return _activity; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AchievementState")]
  public partial class AchievementState : global::ProtoBuf.IExtensible
  {
    public AchievementState() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _percent = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"percent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int percent
    {
      get { return _percent; }
      set { _percent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PveState")]
  public partial class PveState : global::ProtoBuf.IExtensible
  {
    public PveState() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _best = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"best", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int best
    {
      get { return _best; }
      set { _best = value; }
    }
    private int _star = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private int _curCount = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"curCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int curCount
    {
      get { return _curCount; }
      set { _curCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OwnedHeroState")]
  public partial class OwnedHeroState : global::ProtoBuf.IExtensible
  {
    public OwnedHeroState() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _star = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private int _stage = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stage
    {
      get { return _stage; }
      set { _stage = value; }
    }
    private int _skillLevel1 = (int)1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skillLevel1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int skillLevel1
    {
      get { return _skillLevel1; }
      set { _skillLevel1 = value; }
    }
    private int _skillLevel2 = (int)1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"skillLevel2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int skillLevel2
    {
      get { return _skillLevel2; }
      set { _skillLevel2 = value; }
    }
    private int _skillLevel3 = (int)1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"skillLevel3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int skillLevel3
    {
      get { return _skillLevel3; }
      set { _skillLevel3 = value; }
    }
    private int _cskillLevel1 = (int)1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cskillLevel1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int cskillLevel1
    {
      get { return _cskillLevel1; }
      set { _cskillLevel1 = value; }
    }
    private int _cskillLevel2 = (int)1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cskillLevel2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int cskillLevel2
    {
      get { return _cskillLevel2; }
      set { _cskillLevel2 = value; }
    }
    private int _cskillLevel3 = (int)1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"cskillLevel3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int cskillLevel3
    {
      get { return _cskillLevel3; }
      set { _cskillLevel3 = value; }
    }
    private int _exp = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _equip1 = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"equip1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip1
    {
      get { return _equip1; }
      set { _equip1 = value; }
    }
    private int _equip2 = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"equip2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip2
    {
      get { return _equip2; }
      set { _equip2 = value; }
    }
    private int _equip3 = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"equip3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip3
    {
      get { return _equip3; }
      set { _equip3 = value; }
    }
    private int _equip4 = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"equip4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equip4
    {
      get { return _equip4; }
      set { _equip4 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MineState")]
  public partial class MineState : global::ProtoBuf.IExtensible
  {
    public MineState() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GroupDefinition")]
  public partial class GroupDefinition : global::ProtoBuf.IExtensible
  {
    public GroupDefinition() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _icon;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PveCharpter")]
  public partial class PveCharpter : global::ProtoBuf.IExtensible
  {
    public PveCharpter() {}
    
    private int _charpter;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charpter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int charpter
    {
      get { return _charpter; }
      set { _charpter = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _getlevel = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"getlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> getlevel
    {
      get { return _getlevel; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Activity")]
  public partial class Activity : global::ProtoBuf.IExtensible
  {
    public Activity() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _activityCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"activityCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int activityCount
    {
      get { return _activityCount; }
      set { _activityCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}