//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Task.proto
namespace Task
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Task")]
  public partial class Task : global::ProtoBuf.IExtensible
  {
    public Task() {}
    
    private readonly global::System.Collections.Generic.List<Task.SubTask> _mainTask = new global::System.Collections.Generic.List<Task.SubTask>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mainTask", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Task.SubTask> mainTask
    {
      get { return _mainTask; }
    }
  
    private readonly global::System.Collections.Generic.List<Task.SubTask> _branchTask = new global::System.Collections.Generic.List<Task.SubTask>();
    [global::ProtoBuf.ProtoMember(2, Name=@"branchTask", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Task.SubTask> branchTask
    {
      get { return _branchTask; }
    }
  
    private readonly global::System.Collections.Generic.List<Task.SubTask> _dayTask = new global::System.Collections.Generic.List<Task.SubTask>();
    [global::ProtoBuf.ProtoMember(3, Name=@"dayTask", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Task.SubTask> dayTask
    {
      get { return _dayTask; }
    }
  
    private readonly global::System.Collections.Generic.List<Task.SubTask> _weekTask = new global::System.Collections.Generic.List<Task.SubTask>();
    [global::ProtoBuf.ProtoMember(4, Name=@"weekTask", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Task.SubTask> weekTask
    {
      get { return _weekTask; }
    }
  
    private readonly global::System.Collections.Generic.List<Task.TermRecord> _mainTermMap = new global::System.Collections.Generic.List<Task.TermRecord>();
    [global::ProtoBuf.ProtoMember(5, Name=@"mainTermMap", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Task.TermRecord> mainTermMap
    {
      get { return _mainTermMap; }
    }
  
    private readonly global::System.Collections.Generic.List<Task.TermRecord> _dayTermMap = new global::System.Collections.Generic.List<Task.TermRecord>();
    [global::ProtoBuf.ProtoMember(6, Name=@"dayTermMap", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Task.TermRecord> dayTermMap
    {
      get { return _dayTermMap; }
    }
  
    private readonly global::System.Collections.Generic.List<Task.TermRecord> _weekTermMap = new global::System.Collections.Generic.List<Task.TermRecord>();
    [global::ProtoBuf.ProtoMember(7, Name=@"weekTermMap", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Task.TermRecord> weekTermMap
    {
      get { return _weekTermMap; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubTask")]
  public partial class SubTask : global::ProtoBuf.IExtensible
  {
    public SubTask() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _progress;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private int _lastReward;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"lastReward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastReward
    {
      get { return _lastReward; }
      set { _lastReward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TermRecord")]
  public partial class TermRecord : global::ProtoBuf.IExtensible
  {
    public TermRecord() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _currCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"currCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currCount
    {
      get { return _currCount; }
      set { _currCount = value; }
    }
    private readonly global::System.Collections.Generic.List<Task.TermRecord.MapState> _currMap = new global::System.Collections.Generic.List<Task.TermRecord.MapState>();
    [global::ProtoBuf.ProtoMember(3, Name=@"currMap", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Task.TermRecord.MapState> currMap
    {
      get { return _currMap; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapState")]
  public partial class MapState : global::ProtoBuf.IExtensible
  {
    public MapState() {}
    
    private int _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}